<?php

declare(strict_types=1);

namespace Onlineconf\Cdb;

/**
 * Writes the text format (`<module>.conf`) that onlineconf-updater puts next to each CDB file.
 *
 * The library does not read this format; the file is a human-readable listing of the module for
 * `grep` and code review. Layout follows the updater: `#!` header, one `<path> <value>` line per key,
 * JSON values as `<path>:JSON <json>`, an empty value as the key followed by one space, `#EOF` at the end.
 */
final class ConfWriter
{
    /**
     * @param array<string, string> $raw     path → raw value including the type byte
     * @param string|null           $version text of the "#! Version" header line; the current time when null
     */
    public static function write(string $file, string $name, array $raw, ?string $version = null): void
    {
        ksort($raw, SORT_STRING);

        $lines = [
            '# This file is generated by onlineconf-php (Onlineconf\Cdb\ConfWriter); the library reads only the .cdb file',
            '#! Name ' . $name,
            '#! Version ' . ($version ?? date('Y-m-d H:i:s')),
            '',
        ];
        foreach ($raw as $path => $value) {
            $lines[] = $value[0] === 'j' ? $path . ':JSON ' . substr($value, 1) : $path . ' ' . substr($value, 1);
        }
        $lines[] = '#EOF';

        file_put_contents($file, implode("\n", $lines));
    }
}
