<?php

declare(strict_types=1);

namespace Onlineconf\Tests\Support;

/**
 * Writes the legacy text format (`<module>.conf`) that onlineconf-updater puts next to each CDB file.
 *
 * The library does not read this format; the files are generated only as a human-readable listing
 * of the sample modules. Layout follows the updater: `#!` header, one `<path> <value>` line per key,
 * JSON values as `<path>:JSON <json>`, an empty value as the key followed by one space, `#EOF` at the end.
 */
final class ConfWriter
{
    /**
     * @param array<string, string> $raw path → raw value including the type byte
     */
    public static function write(string $file, string $name, array $raw): void
    {
        ksort($raw, SORT_STRING);

        $lines = [
            '# This file is generated by examples/build.php (onlineconf-php); the library reads only the .cdb file',
            '#! Name ' . $name,
            '#! Version 2026-09-07 00:00:00',
            '',
        ];
        foreach ($raw as $path => $value) {
            $lines[] = $value[0] === 'j' ? $path . ':JSON ' . substr($value, 1) : $path . ' ' . substr($value, 1);
        }
        $lines[] = '#EOF';

        file_put_contents($file, implode("\n", $lines));
    }
}
