<?php

declare(strict_types=1);

namespace Onlineconf\Source;

use Onlineconf\Json;
use Onlineconf\Source;

/**
 * Decorator that overrides selected keys of another source; for tests of code that consumes OnlineConf.
 *
 * Keys not overridden are read from the inner source; child lists ("<path>/") are merged, so overridden
 * and new keys appear next to the inner source's children. Every change of the overrides is reported through
 * {@see reloadIfChanged()} and {@see version()}, so a {@see \Onlineconf\Module} built on this source
 * drops its cache; create it with `checkInterval: 0` so that the change is picked up immediately.
 */
final class OverrideSource implements Source
{
    use ChangeTracking;

    /** @var array<string, string> path → raw value including the type byte */
    private array $overrides = [];

    public function __construct(private readonly Source $inner)
    {
    }

    /**
     * Runs the callback with additional overrides in place and restores the previous ones afterwards,
     * also when the callback throws. Returns the callback result.
     *
     * @param array<string, string|int|float|bool|array<mixed>|null> $values path → PHP value (see ArraySource::fromValues());
     *                                                                       child lists are generated and must not be passed
     *
     * @throws \InvalidArgumentException when a child list ("<path>/") is passed
     */
    public function with(array $values, callable $callback): mixed
    {
        $saved = $this->overrides;
        $this->override($values);

        try {
            return $callback();
        } finally {
            $this->set($saved);
        }
    }

    /**
     * Adds overrides that stay until {@see clear()}.
     *
     * @param array<string, string|int|float|bool|array<mixed>|null> $values path → PHP value (see ArraySource::fromValues());
     *                                                                       child lists are generated and must not be passed
     *
     * @throws \InvalidArgumentException when a child list ("<path>/") is passed
     */
    public function override(array $values): void
    {
        $this->set(array_merge($this->overrides, ArraySource::rawFromValues($values)));
    }

    /**
     * Removes all overrides.
     */
    public function clear(): void
    {
        $this->set([]);
    }

    public function getRaw(string $path): ?string
    {
        $override = $this->overrides[$path] ?? null;
        if ($override === null) {
            return $this->inner->getRaw($path);
        }
        if (!str_ends_with($path, '/')) {
            return $override;
        }

        // A child list generated from the overrides names only the overridden keys;
        // the children the inner source knows must stay visible.
        $inner = $this->inner->getRaw($path);

        return $inner === null ? $override : self::mergeChildLists($inner, $override);
    }

    public function reloadIfChanged(): bool
    {
        $innerChanged = $this->inner->reloadIfChanged();

        return $this->consumeChanged() || $innerChanged;
    }

    public function version(): string
    {
        return $this->inner->version() . ':' . $this->generation;
    }

    public function name(): string
    {
        return $this->inner->name();
    }

    private static function mergeChildLists(string $inner, string $override): string
    {
        $names = json_decode(substr($inner, 1), true);
        if (!is_array($names)) {
            return $override;
        }
        /** @var list<string> $added generated by ArraySource::rawFromValues() */
        $added = json_decode(substr($override, 1), true);

        $merged = array_values(array_unique(array_merge(array_filter($names, 'is_string'), $added)));
        sort($merged, SORT_STRING);

        return 'j' . Json::encode($merged);
    }

    /**
     * @param array<string, string> $overrides
     */
    private function set(array $overrides): void
    {
        $this->overrides = $overrides;
        $this->markChanged();
    }
}
